export * from './use-create-record_file'
export * from './use-update-record_file'
export * from './use-get-cover_page'
export * from './use-get-record_files'
export * from './use-get-report'
export * from './use-delete-record-file'
export * from './use-search-deterioration'
export * from './use-search-sections'
export * from'./use-search-funds'
export * from './use-search-locations'
export * from './use-search-series'
export * from './use-search-typologies'
